// Self-service booking against a single Google Calendar, read live on every request.
//
// One calendar holds both sides of the question. Events created by hand are open windows —
// add one from the phone and that window opens on the site. Events written by this Worker are
// bookings, marked with a private extended property Google never shows in the app, and they
// subtract from the windows they sit in. Nothing else is read, so no other calendar is exposed.

import { accessToken } from '../lib/google-auth.js'
import { BREVO_EMAIL, brevo } from '../lib/brevo.js'
import { LIMITS as SHARED_LIMITS, cleanString as clean, isEmail } from '../lib/validate.js'

const SCOPE = 'https://www.googleapis.com/auth/calendar'
const BOOKING_TAG = 'siteBooking'

// Shorter than the contact form's: this text lands in a calendar event description.
const LIMITS = { ...SHARED_LIMITS, message: 2000 }
const MODES = ['online', 'cabinet']

const eventsUrl = (calendarId) =>
    `https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events`

export const bookingConfigured = (env) =>
    Boolean(env.GOOGLE_CALENDAR_SERVICE_ACCOUNT && env.BOOKING_CALENDAR_ID)

function config(env) {
    return {
        calendarId: env.BOOKING_CALENDAR_ID,
        timeZone: env.BOOKING_TIMEZONE || 'Europe/Bucharest',
        slotMinutes: Number(env.BOOKING_SLOT_MINUTES || 50),
        stepMinutes: Number(env.BOOKING_STEP_MINUTES || 60),
        leadHours: Number(env.BOOKING_LEAD_HOURS || 24),
        daysAhead: Number(env.BOOKING_DAYS_AHEAD || 21)
    }
}

const calendarToken = (env) => accessToken(JSON.parse(env.GOOGLE_CALENDAR_SERVICE_ACCOUNT), SCOPE)

async function googleCalendar(env, url, init) {
    const response = await fetch(url, {
        ...init,
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${await calendarToken(env)}`, ...init?.headers }
    })

    if (!response.ok) throw new Error(`Calendar ${response.status}: ${await response.text()}`)

    return response.json()
}

// singleEvents expands repeats, so "every Tuesday 10-14" set once in the app keeps producing
// windows, and deleting a booking in the app frees its slot again.
// ponytail: an untagged event is an open window, so anything added here by hand is offered as
// bookable. Keep this calendar for availability only, or split bookings onto a second one.
async function readCalendar(env, settings, timeMin, timeMax) {
    const query = new URLSearchParams({
        timeMin,
        timeMax,
        singleEvents: 'true',
        orderBy: 'startTime',
        maxResults: '2500'
    })

    const { items = [] } = await googleCalendar(env, `${eventsUrl(settings.calendarId)}?${query}`)

    const windows = []
    const busy = []

    for (const item of items) {
        // All-day entries carry a bare date, which says nothing about which hours are open.
        if (!item.start?.dateTime || !item.end?.dateTime) continue

        const range = [Date.parse(item.start.dateTime), Date.parse(item.end.dateTime)]

        if (item.extendedProperties?.private?.[BOOKING_TAG]) busy.push(range)
        else windows.push(range)
    }

    return { windows, busy }
}

const isFree = (start, end, busy) => busy.every(([from, until]) => end <= from || start >= until)

// The grid is anchored to each window's own start, so a 10:00 window yields 10:00, 11:00, …
function slotsIn(windows, busy, settings, now) {
    const earliest = now + settings.leadHours * 3_600_000
    const length = settings.slotMinutes * 60_000
    const step = settings.stepMinutes * 60_000
    const found = new Set()

    for (const [opens, closes] of windows) {
        for (let start = opens; start + length <= closes; start += step) {
            if (start >= earliest && isFree(start, start + length, busy)) found.add(start)
        }
    }

    return [...found].sort((a, b) => a - b).map((start) => new Date(start).toISOString())
}

// Both reads share this, so the slot list a visitor sees and the list their booking is checked
// against can never be generated by different rules.
async function openSlots(env, settings, now = Date.now()) {
    const { windows, busy } = await readCalendar(
        env,
        settings,
        new Date(now).toISOString(),
        new Date(now + settings.daysAhead * 86_400_000).toISOString()
    )

    return slotsIn(windows, busy, settings, now)
}

export async function availableSlots(env) {
    const settings = config(env)

    return {
        ok: true,
        timeZone: settings.timeZone,
        slotMinutes: settings.slotMinutes,
        slots: await openSlots(env, settings)
    }
}

async function createEvent(env, settings, { start, end, name, email, phone, mode, message, consentText }) {
    await googleCalendar(env, eventsUrl(settings.calendarId), {
        method: 'POST',
        body: JSON.stringify({
            summary: `Ședință: ${name}`,
            // Never an `attendees` entry: a service account cannot invite anyone without
            // domain-wide delegation, which a personal Gmail account cannot grant.
            description: [
                `Nume: ${name}`,
                `Email: ${email}`,
                `Telefon: ${phone}`,
                `Modalitate: ${mode === 'online' ? 'Online' : 'La cabinet'}`,
                message ? `\nMesaj:\n${message}` : null,
                `\nProgramare făcută de pe site. Consimțământ: ${clean(consentText, LIMITS.consentText)}`
            ]
                .filter((line) => line !== null)
                .join('\n'),
            start: { dateTime: start, timeZone: settings.timeZone },
            end: { dateTime: end, timeZone: settings.timeZone },
            // What separates a booking from an open window. Private to this calendar's copy of
            // the event, and never rendered in the Google Calendar app.
            extendedProperties: { private: { [BOOKING_TAG]: '1' } }
        })
    })
}

const formatSlot = (iso, timeZone) =>
    new Intl.DateTimeFormat('ro-RO', { timeZone, dateStyle: 'full', timeStyle: 'short' }).format(new Date(iso))

async function notify(env, settings, { name, email, phone, mode, message, start }) {
    const when = formatSlot(start, settings.timeZone)
    const place = mode === 'online' ? 'Online' : 'La cabinet'

    await brevo(BREVO_EMAIL, env.BREVO_API_KEY, {
        sender: { email: env.CONTACT_FROM_EMAIL, name: 'Programări site' },
        to: [{ email: env.CONTACT_TO_EMAIL }],
        replyTo: { email, name },
        subject: `Programare nouă: ${name} — ${when}`,
        textContent: [
            `${name} a rezervat o ședință.`,
            '',
            `Când: ${when} (${settings.timeZone})`,
            `Durată: ${settings.slotMinutes} de minute`,
            `Modalitate: ${place}`,
            `Email: ${email}`,
            `Telefon: ${phone}`,
            message ? `\nMesaj:\n${message}` : null,
            '',
            'Ședința este deja în calendar.'
        ]
            .filter((line) => line !== null)
            .join('\n')
    })

    await brevo(BREVO_EMAIL, env.BREVO_API_KEY, {
        sender: { email: env.CONTACT_FROM_EMAIL, name: 'Andreea Butacu' },
        to: [{ email, name }],
        replyTo: { email: env.CONTACT_TO_EMAIL },
        subject: `Programarea ta: ${when}`,
        textContent: [
            `Bună, ${name},`,
            '',
            `Ședința ta este confirmată pentru ${when} (ora României).`,
            `Durată: ${settings.slotMinutes} de minute. Modalitate: ${place}.`,
            '',
            'Dacă vrei să muți sau să anulezi ședința, răspunde la acest email.',
            '',
            'Pe curând,',
            'Andreea'
        ].join('\n')
    })
}

export async function handleBooking(data, env) {
    if (!bookingConfigured(env)) return { ok: false, error: 'not_configured' }

    const settings = config(env)

    const email = clean(data.email, LIMITS.email)
    const name = clean(data.name, LIMITS.name)
    const phone = clean(data.phone, LIMITS.phone)
    const message = clean(data.message, LIMITS.message)
    const mode = MODES.includes(data.mode) ? data.mode : MODES[0]
    const start = clean(data.start, 40)

    if (!isEmail(email) || !name || !phone) return { ok: false, error: 'invalid_fields' }

    // Re-derived rather than trusted: without this the form is a write handle on the calendar,
    // and it doubles as the check that nobody took the slot since the page was loaded.
    // ponytail: not a lock, so two people submitting the same slot in the same second both get
    // it. Move to a KV hold if that ever actually happens.
    if (!(await openSlots(env, settings)).includes(start)) return { ok: false, error: 'slot_unavailable' }

    const end = new Date(Date.parse(start) + settings.slotMinutes * 60_000).toISOString()
    const booking = { start, end, name, email, phone, mode, message }

    await createEvent(env, settings, { ...booking, consentText: data.consentText })

    // The event is the booking and it is already held. A mail outage must not undo it, and the
    // browser has shown the visitor their time either way.
    await notify(env, settings, booking).catch((error) => console.error('booking email failed', error))

    return { ok: true, start, end }
}
